---
- name: install apache
  apt: name=apache2 state=present
- name: Copy new virtual host file
  template:
    src=virtual-hosts.conf.j2
    dest=/etc/apache2/sites-available/vagrant.conf
- name: Remove default virtual hosts
  file:
    path=/etc/apache2/sites-enabled/000-default.conf
    state=absent
  notify:
    - reload apache server
- name: Enable news vagrant virtual host
  file:
    src=/etc/apache2/sites-available/vagrant.conf
    dest=/etc/apache2/sites-enabled/vagrant.conf
    state=link
  notify:
    - reload apache server
- name: Enable mod_rewrite module
  apache2_module:
    state: present
    name: rewrite
